FROM almalinux/9-base:latest

WORKDIR /code

COPY alws/scripts/albs-gitea-listener/requirements.txt .
RUN <<EOT
  set -ex
  export LANG=C.UTF-8
  export LC_ALL=C.UTF-8
  python3 -m ensurepip
  pip3 install -r requirements.txt
  rm requirements.txt
EOT

COPY alws/scripts/git_cacher/requirements.txt .
RUN <<EOT
  set -ex
  export LANG=C.UTF-8
  export LC_ALL=C.UTF-8
  pip3 install -r requirements.txt
  rm requirements.txt
EOT
