FROM almalinux/9-base:latest

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

WORKDIR /code

COPY alws/scripts/albs-gitea-listener/requirements.txt .
RUN <<EOT
  set -ex
  python3 -m ensurepip
  pip3 install -r requirements.txt
  rm requirements.txt
EOT

COPY alws/scripts/git_cacher/requirements.txt .
RUN <<EOT
  set -ex
  pip3 install -r requirements.txt
  rm requirements.txt
EOT
